#!/usr/bin/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Run artisan scheduled tasks.
#======================================================================================================================

php ${FREESCOUT_SRC}/artisan queue:restart
php ${FREESCOUT_SRC}/artisan freescout:update-folder-counters
freescout-set-permissions > /dev/null 2>&1
