#!/bin/sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Install PHP dependencies.
#======================================================================================================================

apk add --no-cache \
    php8-curl=${1} \
    php8-dom=${1} \
    php8-fileinfo=${1} \
    php8-gd=${1} \
    php8-iconv=${1} \
    php8-imap=${1} \
    php8-mbstring=${1} \
    php8-mysqli=${1} \
    php8-mysqlnd=${1} \
    php8-pdo_mysql=${1} \
    php8-tokenizer=${1} \
    php8-xml=${1} \
    php8-zip=${1}
bf-done
