#!/bin/withenv sh

set -euo pipefail


#======================================================================================================================
# Run task scheduler as a service.
# This is because on Alpine the scheduler doesn't work correctly when run through the cron.
#======================================================================================================================

bf-write "Running FreeScout task scheduler."
SRC=$(bf-env FS_SRC)
php ${SRC}/artisan schedule:run >> /dev/null 2>&1
