#!/usr/bin/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Add environment variables.
#======================================================================================================================

FREESCOUT_SRC=${BF_SRC}/freescout
bf-env "FREESCOUT_SRC" "${FREESCOUT_SRC}"
bf-env "NGINX_ROOT" "${FREESCOUT_SRC}/public"
