#!/usr/bin/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Add environment variables.
#======================================================================================================================

bf-env "FREESCOUT_LIB" "${BF_LIB}/freescout"

bf-env "FREESCOUT_ENV" "${FREESCOUT_SRC}/.env"
