#!/usr/bin/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# If FREESCOUT_ENV doesn't exist, the source files have not been downloaded correctly.
#======================================================================================================================

[[ ! -f ${FREESCOUT_ENV} ]] && bf-error "${FREESCOUT_ENV} does not exist."


#======================================================================================================================
# Run setup config executable.
#======================================================================================================================

${FREESCOUT_LIB}/setup-config
freescout-setup-complete
