#!/usr/bin/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# If FREESCOUT_ENV_SRC doesn't exist, the setup has gone wrong.
#======================================================================================================================

[[ ! -L ${FREESCOUT_ENV_SRC} ]] && bf-error "${FREESCOUT_ENV_SRC} is not linked correctly."


#======================================================================================================================
# Run setup artisan executable.
#======================================================================================================================

${FREESCOUT_LIB}/setup-artisan
freescout-setup-complete
