#!/usr/bin/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# If setup completed succesfully, write nice message and exit.
#======================================================================================================================

if [ "${SETUP_COMPLETE-}" = "1" ] ; then
    bf-clear
    bf-ok "FreeScout setup complete."
    exit 0
fi


#======================================================================================================================
# If we weren't taking over an existing installation, delete .env file to be regenerated next time.
#======================================================================================================================

[[ "${FREESCOUT_INSTALLED-}" != "1" ]] && rm "${FREESCOUT_ENV}"


#======================================================================================================================
# Terminate the container.
#======================================================================================================================

bf-notok "FreeScout setup did not complete successfully, terminating container."
bf-svc-terminate
