#!/usr/bin/with-contenv bash

set -euo pipefail
export BF_E="${PWD##*/}/$(basename ${0})"


#======================================================================================================================
# Fetch emails manually.
# This is because on Alpine the scheduler doesn't fetch emails correctly.  Tasks are defined in:
# https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Kernel.php
#======================================================================================================================

sleep 60
php ${FREESCOUT_SRC}/artisan freescout:fetch-emails >> /data/storage/logs/fetch-emails.log
