#!/bin/sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Install PHP dependencies.
#======================================================================================================================

apk add --no-cache \
    php81-curl=${1} \
    php81-dom=${1} \
    php81-fileinfo=${1} \
    php81-gd=${1} \
    php81-iconv=${1} \
    php81-imap=${1} \
    php81-intl=${1} \
    php81-mbstring=${1} \
    php81-mysqli=${1} \
    php81-mysqlnd=${1} \
    php81-pdo_mysql=${1} \
    php81-tokenizer=${1} \
    php81-xml=${1} \
    php81-xmlwriter=${1} \
    php81-zip=${1}
bf-done
