#!/usr/bin/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Generate config from environment variables.
#======================================================================================================================

# ensure all required environment variables are set
[[ -z "${FREESCOUT_APP_URL-}" ]] && bf-error "FREESCOUT_APP_URL must be set."
[[ -z "${FREESCOUT_DB_NAME-}" ]] && bf-error "FREESCOUT_DB_NAME must be set."
[[ -z "${FREESCOUT_DB_USER-}" ]] && bf-error "FREESCOUT_DB_USER must be set."
[[ -z "${FREESCOUT_DB_PASS-}" ]] && bf-error "FREESCOUT_DB_PASS must be set."
[[ -z "${FREESCOUT_DB_HOST-}" ]] && bf-error "FREESCOUT_DB_HOST must be set."

# generate config from the template
bf-debug "Generating ${FREESCOUT_ENV}."
esh -o ${FREESCOUT_ENV} \
    ${BF_TEMPLATES}/.env.esh

# run artisan setup
bf-debug "Running artisan setup."
cd ${FREESCOUT_SRC}
php artisan key:generate
php artisan freescout:clear-cache
php artisan storage:link
php artisan migrate
php artisan freescout:create-user

bf-done
