#!/usr/bin/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Generate config from environment variables.
#======================================================================================================================

# ensure all required environment variables are set
[[ -z "${FREESCOUT_APP_URL-}" ]] && bf-error "FREESCOUT_APP_URL must be set."
[[ -z "${FREESCOUT_DB_NAME-}" ]] && bf-error "FREESCOUT_DB_NAME must be set."
[[ -z "${FREESCOUT_DB_USER-}" ]] && bf-error "FREESCOUT_DB_USER must be set."
[[ -z "${FREESCOUT_DB_PASS-}" ]] && bf-error "FREESCOUT_DB_PASS must be set."
[[ -z "${FREESCOUT_DB_HOST-}" ]] && bf-error "FREESCOUT_DB_HOST must be set."
[[ -z "${FREESCOUT_ADMIN_FIRSTNAME-}" ]] && bf-error "FREESCOUT_ADMIN_FIRSTNAME must be set."
[[ -z "${FREESCOUT_ADMIN_LASTNAME-}" ]] && bf-error "FREESCOUT_ADMIN_LASTNAME must be set."
[[ -z "${FREESCOUT_ADMIN_EMAIL-}" ]] && bf-error "FREESCOUT_ADMIN_EMAIL must be set."
[[ -z "${FREESCOUT_ADMIN_PASS-}" ]] && bf-error "FREESCOUT_ADMIN_PASS must be set."

# generate config from the template
bf-debug "Generating ${FREESCOUT_ENV}."
esh -o ${FREESCOUT_ENV} \
    ${BF_TEMPLATES}/.env.esh

# run artisan setup
cd ${FREESCOUT_SRC}

bf-debug "Generate key."
php artisan key:generate

bf-debug "Clear cache."
php artisan freescout:clear-cache

bf-debug "Link storage."
php artisan storage:link

bf-debug "Migrate database."
php artisan migrate --force

bf-debug "Create admin user."
php artisan -n freescout:create-user \
    --role=admin \
    --firstName="${FREESCOUT_ADMIN_FIRSTNAME}" \
    --lastName="${FREESCOUT_ADMIN_LASTNAME}" \
    --email="${FREESCOUT_ADMIN_EMAIL}" \
    --password="${FREESCOUT_ADMIN_PASS}"

bf-done
