#!/command/with-contenv bash

set -euo pipefail


#======================================================================================================================
# Run artisan setup routines, skipping key and user creation if app has already been set up.
#======================================================================================================================

bf-echo "Run artisan setup." "freescout/setup-artisan"

cd ${FREESCOUT_SRC}

if [ "${FREESCOUT_EXISTING_INSTALLATION-}" -ne "1" ] ; then
    bf-debug "Generate key." "freescout/setup-artisan"
    php artisan key:generate
fi

bf-debug "Clear cache." "freescout/setup-artisan"
php artisan freescout:clear-cache

bf-debug "Clear config." "freescout/setup-artisan"
php artisan config:clear

# we don't use artisan storage:link because we've moved the storage location

bf-debug "Migrate database." "freescout/setup-artisan"
php artisan migrate --force

if [ "${FREESCOUT_EXISTING_INSTALLATION-}" -ne "1" ] ; then

    # ensure all required environment variables are set
    [[ -z "${FREESCOUT_ADMIN_FIRSTNAME-}" ]] && bf-error "FREESCOUT_ADMIN_FIRSTNAME must be set." "freescout/setup-artisan"
    [[ -z "${FREESCOUT_ADMIN_LASTNAME-}" ]] && bf-error "FREESCOUT_ADMIN_LASTNAME must be set." "freescout/setup-artisan"
    [[ -z "${FREESCOUT_ADMIN_EMAIL-}" ]] && bf-error "FREESCOUT_ADMIN_EMAIL must be set." "freescout/setup-artisan"
    [[ -z "${FREESCOUT_ADMIN_PASS-}" ]] && bf-error "FREESCOUT_ADMIN_PASS must be set." "freescout/setup-artisan"

    bf-debug "Create admin user." "freescout/setup-artisan"
    php artisan -n freescout:create-user \
        --role=admin \
        --firstName="${FREESCOUT_ADMIN_FIRSTNAME}" \
        --lastName="${FREESCOUT_ADMIN_LASTNAME}" \
        --email="${FREESCOUT_ADMIN_EMAIL}" \
        --password="${FREESCOUT_ADMIN_PASS}"

fi

bf-done "freescout/setup-artisan"
