#!/bin/bash

set -euo pipefail


#======================================================================================================================
# Delete a file or directory if it is not a link.
#
# Arguments
#   1   File / directory path
#======================================================================================================================

delete-if-not-link () {

    CHECK_PATH=${1}
    if [ ! -L "${CHECK_PATH}" ] ; then
        bf-debug " .. deleting ${CHECK_PATH} so it can be turned into a symlink." "freescout/setup-content"
        rm -rf ${CHECK_PATH}
    fi

}


#======================================================================================================================
# Move a file or directory if it is not a link.
#
# Arguments
#   1   File / directory path
#======================================================================================================================

move-if-not-link () {

    CHECK_PATH=${1}
    if [ ! -L "${CHECK_PATH}" ] ; then
        bf-debug " .. moving ${CHECK_PATH}" "freescout/setup-content"
        mv ${CHECK_PATH} ${FREESCOUT}
    fi

}


#======================================================================================================================
# If .env already exists, delete source content so it can be linked to /data content...
#======================================================================================================================

if [ -f "${FREESCOUT_ENV}" ] ; then

    bf-echo "Taking over an existing installation - remove source directories to create links." "freescout/setup-content"

    delete-if-not-link "${FREESCOUT_ENV_SRC}"
    delete-if-not-link "${FREESCOUT_MODULES_SRC}"
    delete-if-not-link "${FREESCOUT_STORAGE_SRC}"
    bf-done "freescout/setup-content"

    bf-env "FREESCOUT_EXISTING_INSTALLATION" "1" "freescout/setup-content"


#======================================================================================================================
# ...otherwise, move source content to /data.
#======================================================================================================================

else

    bf-echo "New installation - move source directories to ${FREESCOUT}." "freescout/setup-content"

    move-if-not-link ${FREESCOUT_MODULES_SRC}
    move-if-not-link ${FREESCOUT_STORAGE_SRC}
    bf-done "freescout/setup-content"

fi
