#!/usr/bin/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Run artisan setup routines, skipping key and user creation if app has already been set up.
#======================================================================================================================

cd ${FREESCOUT_SRC}

if [ "${FREESCOUT_INSTALLED-}" -ne "1" ] ; then
    bf-debug "Generate key."
    php artisan key:generate
fi

bf-debug "Clear cache."
php artisan freescout:clear-cache

bf-debug "Clear config."
php artisan config:clear

# we don't use artisan storage:link because we've moved the storage location

bf-debug "Migrate database."
php artisan migrate --force

if [ "${FREESCOUT_INSTALLED-}" -ne "1" ] ; then

    bf-debug "Create admin user."
    php artisan -n freescout:create-user \
        --role=admin \
        --firstName="${FREESCOUT_ADMIN_FIRSTNAME}" \
        --lastName="${FREESCOUT_ADMIN_LASTNAME}" \
        --email="${FREESCOUT_ADMIN_EMAIL}" \
        --password="${FREESCOUT_ADMIN_PASS}"

    bf-done

fi

bf-debug "Install modules:"
for m in ${FREESCOUT_MODULES}/* ; do
    [[ -d "$m" ]] \
        && bf-debug "  $m" \
        && php artisan freescout:module-install "$m"
done
