#!/usr/bin/with-contenv bash

set -euo pipefail
export BF_E="${PWD##*/}/$(basename ${0})"


#======================================================================================================================
# Run /usr/local/bin/freescout-schedule-run executable.
#======================================================================================================================

freescout-schedule-run
