#!/bin/sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Install PHP dependencies.
#======================================================================================================================

apk add --no-cache \
    php7-curl=${PHP_VERSION} \
    php7-dom=${PHP_VERSION} \
    php7-fileinfo=${PHP_VERSION} \
    php7-gd=${PHP_VERSION} \
    php7-imap=${PHP_VERSION} \
    php7-json=${PHP_VERSION} \
    php7-ldap=${PHP_VERSION} \
    php7-mbstring=${PHP_VERSION} \
    php7-mysqli=${PHP_VERSION} \
    php7-pdo_mysql=${PHP_VERSION} \
    php7-tokenizer=${PHP_VERSION} \
    php7-xml=${PHP_VERSION} \
    php7-zip=${PHP_VERSION}
bf-done
