#!/bin/sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Install PHP dependencies.
#======================================================================================================================

apk add --no-cache \
    php7-curl@edgetest=${1} \
    php7-dom@edgetest=${1} \
    php7-fileinfo@edgetest=${1} \
    php7-gd@edgetest=${1} \
    php7-iconv@edgetest=${1} \
    php7-imap@edgetest=${1} \
    php7-json@edgetest=${1} \
    php7-ldap@edgetest=${1} \
    php7-mbstring@edgetest=${1} \
    php7-mysqli@edgetest=${1} \
    php7-pdo_mysql@edgetest=${1} \
    php7-tokenizer@edgetest=${1} \
    php7-xml@edgetest=${1} \
    php7-zip@edgetest=${1}
bf-done
