#!/bin/withenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Fetch emails manually.
# This is because on Alpine the scheduler doesn't fetch emails correctly.
#======================================================================================================================

SRC=$(bf-env FS_SRC)
LOG=$(bf-env FS_LOGS)
php ${SRC}/artisan freescout:fetch-emails >> ${LOG}/fetch-emails.log
