#!/usr/bin/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Run artisan scheduled tasks.
# This is because on Alpine the scheduler doesn't run correctly.  Tasks are defined in:
# https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Kernel.php
#======================================================================================================================

php ${FREESCOUT_SRC}/artisan freescout:fetch-emails >> /data/storage/logs/fetch-emails.log
