#!/usr/bin/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Run artisan scheduled tasks.
#======================================================================================================================

php ${FREESCOUT_SRC}/artisan queue:work --queue='emails,default' --sleep=5 --tries=1 >> /dev/null 2>&1
