#!/bin/withenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Ensure permissions are set correctly.
#======================================================================================================================

sleep 30
nu -c "use bf-freescout perms ; perms set" >> /dev/null 2>&1
