#!/usr/bin/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Ensure permissions are set correctly.
#======================================================================================================================

sleep 30
freescout-set-permissions >> /dev/null 2>&1
